local hero1 = getHero(0).getName()
local hero2 = getHero(1).getName()
local hero3 = getHero(2).getName()
local hero4 = getHero(3).getName()

speak("????", "Is someone there? Help!")
speak(hero1, "Jonas? We're coming!")

walk('hero', 4, 'EAST', true)
face('hero', 'NORTH')
walk('dunn', 4, 'SOUTH', true)

speak(hero4, "You're not Jonas.")
speak("Man", "Jonas? He was imprisoned with me.")
speak(hero2, "Well, we'll try to get you out of here.")

face('hero', 'EAST')
speak("????", "Jonas! Are you there?")
sceneSwitch('lara_appears', true)
walk('lara', 1, 'NORTH', true)
walk('lara', 6, 'WEST', true)
walk('lara', 1, 'WEST', false)
walk('hero', 1, 'WEST', true)
face('hero', 'EAST')

speak("????", "You're not Jonas.")
speak(hero1, "No, of course not. We came here to free Jonas. Who are you?")
speak("????", "Lara.")
speak("Lara", "How do you know Jonas?")
speak(hero1, "He's my brother. Not by blood, but close enough.")
speak("Lara", "Jonas and I are comrades... but I'm not sure I should say more.")
speak(hero1, "And what of Janine?")
speak("Lara", "Who?")
speak(hero1, "...")
speak("Man", "Jonas was moved to the castle of the worm.")
speak(hero3, "Why? I thought the wolf and worm were enemies.")
speak("Lara", "Why don't we ask the wolf himself? Come!")

pathEvent('lara', 'hero')
addMember('chara_lara')
sceneSwitch('lara_joins', true)
