sceneSwitch('machine_chest', true)
playSound('get')
speak("Retrieved the $CSPEED.")
addItem('hand_speed')
wait(0.7)
playBGM('ffl2_save_the_world')
speak("????", "INTRUDER ALERT. PREPARE THE SECURITY SYSTEM.")
sceneSwitch('machine2_dead', true)
battle('party_bossMachine2', true, 'ffl2_save_the_world')
playBGM('ffl3_dungeon')
