local hero1 = getHero(0).getName()
local hero2 = getHero(1).getName()
local hero3 = getHero(2).getName()
local hero4 = getHero(3).getName()

speak("Jonas", hero1 .. ", what are you doing here?")
speak(hero1, "We're looking for the legendary swords.")
speak(hero2, "What happened here?")
speak("Jonas", "The monks here kept the sword EMPEROR, but it seems Moloch found them...")
speak("Jonas", "I was too late to help the monks, but at least I ran into you. We need to destroy the swords to stop the masters.")
speak("Jonas", "Or has Janine told you otherwise?")
speak(hero4, "Well...")
speak("Jonas", "It doesn't matter. Let's work together if we can.")
speak(hero3, "Is Moloch strong?")
speak("Jonas", "The people of this world pay him tribute and he becomes stronger. And now that he has EMPEROR...")
speak("Jonas", "We need to find a way through the wastes and into his lair.")
speak(hero1, "How can we help?")
speak("Jonas", "I'll look for a way to Moloch's base. You try to find the other two swords.")
speak("Jonas", "When I find something, I'll meet you at the underground city.")
speak(hero1, "It's a plan! I'm glad we're on the same side.")
speak("Jonas", "Me too.")

walk('jonas', 1, 'EAST')
walk('jonas', 9, 'NORTH')

sceneSwitch('jonas01', true)
