local hero1 = getHero(0).getName()
local hero2 = getHero(1).getName()
local hero3 = getHero(2).getName()
local hero4 = getHero(3).getName()

sceneSwitch('temple_jonas', true)

walk('jonas', 9, 'SOUTH')
face('hero', 'EAST')
walk('jonas', 1, 'WEST')

speak("Jonas", hero1 .. "! You beat me here, but I think we're too late.")
speak(hero1, "Jonas! It's good to see you, but... What happened here?")
speak("Jonas", "I came here following Janine's trail. I think Janine, the prince, and this world's master Moloch are after EXCALIBER.")
speak("Jonas", "The monks here kept a part so I was wondering if they'd seen her, but...")
speak(hero3, "A master got here first.")
speak("Jonas", "We're too late to help the monks, but at least we met up. Aven said my priority is to secure EXCALIBER, even more than finding Janine.")
speak("Jonas", "Will you help me and the brotherhood? Don't tell me Janine already got to you.")
speak(hero4, "Well...")
speak("Jonas", "It doesn't matter. Let's work together if we can.")
speak(hero2, "Have you found parts of EXCALIBER?")
speak("Jonas", "No, but now we know Moloch has at least one. We need to find a way through the wastes and into his lair.")
speak(hero1, "How can we help?")
speak("Jonas", "I'll look for a way to Moloch's base. You try to find the other two pieces.")
speak("Jonas", "When I find something, I'll meet you at the underground city.")
speak(hero1, "It's a plan! I'm glad we're on the same side.")
speak("Jonas", "Me too.")
walk('jonas', 1, 'EAST')
walk('jonas', 9, 'NORTH')

sceneSwitch('temple_jonas', false)
sceneSwitch('jonas01', true)
