walk('guard_l1', 2, 'EAST', false)
walk('guard_r1', 2, 'WEST')
face('guard_l1', 'NORTH')
face('guard_r1', 'NORTH')

playSound('explode')
sceneSwitch('missile_trap01_01', true)
shake(0.5, 4)
wait(0.5)
playSound('explode')
sceneSwitch('missile_trap01_02', true)
shake(0.5, 4)
wait(0.5)

sceneSwitch('missile_trap01', true)
