local hero1 = getHero(0).getName()
local hero2 = getHero(2).getName()
local hero3 = getHero(3).getName()

speak("Barkeep", "A drink?")
speak(hero1, "I'm looking for twins, named Jonas and Janine.")
speak("Barkeep", "Jonas! A man by that name came from the gate.")
speak(hero3, "That must be him!")
speak("Barkeep", "I hope he's no friend of yours. He was arrested as a traitor against the world wolf and taken to the wolf's castle.")
speak("Barkeep", "With luck that scum will be executed soon.")
speak(hero2, "How terrible!")
