local hero1 = getHero(0).getName()
local hero2 = getHero(1).getName()
local hero3 = getHero(2).getName()
local hero4 = getHero(3).getName()

playBGM('twins_theme')

speak(hero1, "Jonas! Janine!")
speak("Janine", "Stay back, " .. hero1 .. ".")
pathEvent('hero', 'herosquare')
wait(1.0)

speak("Prince", "You're a fool, Jonas. That piece of EXCALIBUR is fake. I couldn't care less if you destroy it.")
speak("Jonas", "What? No... But you're too late.")
speak("Jonas", hero1 .. " showed up and soon Aven and the brotherhood will be here to finish you off. And you still can't break Babel's seal.")
speak("Prince", "Oh? I don't need EXCALIBUR any more. I have MASAMUNE.")
speak(hero1, "Janine! You wouldn't give it to him!")
speak("Janine", "No need. I'll break the seal myself.")

walk('janine', 3, 'EAST')
face('janine', 'NORTH')
wait(1.0)
playSound('roar')
shake(0.5, 5)
wait(0.7)
face('janine', 'SOUTH')

speak("Jonas", "Janine! You monster! What have you done?")
speak("Janine", "I'm sorry you'll never understand, Jonas.")
speak("Prince", "You've done well, Janine, but I'm afraid I have no more use for you. Say your prayers!")
speak("Jonas", "No!")

walk('prince', 2, 'EAST', false)
walk('jonas', 2, 'WEST', false)
fade('white')
wait(0.5)
playSound('knife')
wait(0.5)
face('prince', 'NORTH')
sceneSwitch('jonas_dead', true)
fade('normal')
wait(1.0)

speak("Janine", "Jonas... You didn't have to...")
speak("Prince", "Tragic, but irrelevant.")
face('prince', 'SOUTH')
speak("Prince", "The seal is broken and I'll become a true god. But first, for the rest of you.")

sceneSwitch('prince_dead', true)
battle('party_bossLucifer', false, 'battle_lucifer')
face('hero', 'NORTH')
playBGM('tower')

walk('hero', 1, 'NORTH')
speak(hero1, "Is he alright?")
face('janine2', 'SOUTH')
speak("Janine", "Jonas is dead.")
speak("Janine", "I was a fool. The masters aren't immortal... You never needed swords or Babel to stop them. Babel is only evil.")
speak("???", "A useful evil.")

walk('aven', 3, 'NORTH')
face('hero', 'SOUTH')
walk('aven', 4, 'NORTH')

speak(hero1, "Aven! You have to help! The prince is dead, but he killed Jonas and the seal is broken!")
speak("Aven", "Is it?")

pathEvent('aven', 'avensquare')
face('hero', 'NORTH')
face('janine2', 'NORTH')
wait(1.0)
face('aven', 'SOUTH')

speak("Aven", "Perfect. Good work, " .. hero1 .. ". The brotherhood was having trouble, but I knew I could count on you.")
speak(hero1, "What are you talking about? Shouldn't you reseal the door?")
speak("Aven", "These were never my seals. They were to prevent people like me from stealing the masters' power.")
speak("Aven", "But now all the masters are slain or sealed by their own magic. You've opened the path for my ascension.")
speak("Aven", "I'm sorry Jonas is dead, but he'll be remembered. Thank you, " .. hero1 .. ". When I'm a god, maybe I'll even grant you a wish!")
speak(hero1, "Stop!")

walk('aven', 1, 'NORTH')
sceneSwitch('aven_revealed', true)

speak('Janine', "The villain! I knew not to trust that man!")
speak(hero1, "Hurry! We have to stop him, in Jonas's name.")

pathEvent('janine2', 'hero')
sceneSwitch('janine_joined', true)
addMember('chara_janine')
