local hero1 = getHero(0).getName()
local hero2 = getHero(1).getName()
local hero3 = getHero(2).getName()
local hero4 = getHero(3).getName()

walk('hero', 2, 'WEST', false)
wait(0.3)
face('aven', 'EAST')
walk('zkauba', 1, 'NORTH')
walk('zkauba', 1, 'EAST')

speak("????", "What are you doing here?")
speak(hero2, "Er...")
speak(hero1, "We're looking for friends of a man named Jonas. Would you -")
speak("????", "Jonas! How do you know him?")
speak(hero3, "Well -")
speak("????", "But first! I'm Zkauba, head of the resistance and second-in-command of the Brotherhood!")
speak(hero1, "Our pleasure. My name is -")
speak("Zkauba", "And this is the great sage Aven, founder of the Brotherhood.")
speak("Aven", "Greetings, friends of Jonas.")
speak("Zkauba", "What has become of him? He and Lara left months ago.")
speak(hero1, "Jonas was injured in another world in Babel. Lara is caring for him.")
speak("Aven", "I'm glad to hear he's alive.")
speak(hero2, "Lara told us you would know how to best fight the masters.")
speak("Aven", "The masters, yes...")
speak("Aven", "The masters are very different, but all want to use Babel to their ends.")
speak("Aven", "They are all destroyers, malevolent beings that inevitably destroy the world they live in. So to live, they need to find fresh victim worlds.")
speak("Zkauba", "Monsters! And to think a master claims this world!")
speak("Aven", "I've been following the prince for a long time. I think he and the masters are best fought by sealing the gates to Babel. Then all worlds are safe.")
speak("Aven", "The City of Angels and its prince are close to tearing open a gate. We must slow them down until I find a way to strengthen the seal.")
speak(hero4, "Can we help?")
speak("Aven", "With Jonas and Lara away, we need all the help we can get.")
speak("Zkauba", "Come with me to the research base on the east coast. Aven believes if we can kidnap the head scientists, the prince can be stopped.")
speak(hero1, "We're in!")

pathEvent('zkauba', 'hero')

sceneSwitch('zkauba_joins', true)
sceneSwitch('aven01', true)
