local hero1 = getHero(0).getName()
local hero2 = getHero(3).getName()

speak("Aven", "How goes the mission to the research base?")
speak(hero2, "We leave for the east coast soon.")
speak("Aven", "...Hm. You say you are from the same world as Jonas?")
speak(hero1, "Yes.")
speak("Aven", "Then maybe you remember a seal on the gate of Hero?")
speak("Aven", "That was my work.")
speak(hero2, "Of course, the mirror!")
speak(hero1, "Best not mention it...")
