local hero1 = getHero(0).getName()
local hero2 = getHero(1).getName()
local hero3 = getHero(2).getName()
local hero4 = getHero(3).getName()

speak(hero1, "Janine!")
speak("Janine", hero1 .. "! I thought you might come here.")
speak(hero1, "What are you up to? And what happened with you and Jonas? And why do you work for the prince?")
speak("Janine", "Slow down! I don't work for the prince, not any more. I just needed to open the gate.")
speak(hero2, "The gate is open?")
speak("Janine", "It only takes a bit of the machine's power to pass through. I think I have what I need.")
speak(hero3, "To do what?")
speak("Janine", "I'm going back to Babel. There is something powerful at the heart of Babel I think I can use to defeat the masters.")
speak(hero1, "Aven says we need to protect the seals on the gates.")
speak("Janine", "The Brotherhood is a bunch of cowards.")
speak(hero4, "But what if the masters find Babel's heart first?")
speak("Janine", "That's why I have to hurry! I've seen entire worlds in ruins... I can't let that happen while we sit here sealing gates!")
speak("Janine", "Good luck, " .. hero1 .. ", but if you've sided with the Brotherhood, I can do it on my own.")
speak(hero1, "Janine! Wait!")

walk('janine', 1, 'NORTH')
face('hero', 'NORTH')
pathEvent('janine', 'target1')
pathEvent('janine', 'target2')
wait(1.0)

speak(hero2, "Come on, " .. hero1 .. ", let's do our job here.")
sceneSwitch('janine02', true)
