fade('white')
wait(1.0)
teleport('hero/demo.tmx', 11, 11, 'NORTH', false)
fade('normal')
wait(1.0)
speak("This is the end of the SaGa4 demo. We've hope you've enjoyed playing the game so far, and hope you follow the game for more updates...")
speak("...and the true secret of the gate!")
fade('white')
wait(1.0)
teleport('hero/gate.tmx', 26, 17, 'SOUTH', false)
fade('normal')